version: '3.8'

services:
  telegram-bot:
    image: ghcr.io/bartixxx32/oneplus-antirollchecker-bot:latest
    container_name: oneplus_arb_bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - GITHUB_PAT=${GITHUB_PAT}
      - STATS_FILE=/data/stats.json
    volumes:
      - bot_data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  bot_data:
